/**
 * ─── CODING PROBLEM TYPES (admin console) ────────────────────────────────────
 *
 * Mirrors the backend's `coding.problem` responses — `AdminProblemController` and the
 * `ProblemDetailResponse` / `ProblemSummaryResponse` records.
 *
 * docs/CODING_PROBLEMS_MASTER_PLAN.md §5.4 is the screen these serve.
 *
 * ─── ⚠ ProblemDetail CONTAINS THE ANSWERS ────────────────────────────────────
 *
 * `testCases[].expected` and `solutions` are the reference implementations. That is correct for
 * this console — a reviewer cannot judge a problem without seeing whether its solution is
 * plausible — and it is the reason every route here is behind PERM_PUBLISH_PROBLEM.
 *
 * The SOLVER's view of a problem is a different response from a different endpoint. Nothing in
 * this file should ever be reused there.
 */

/** Spring `Page<T>` — only the fields this console reads. */
export interface PagedResponse<T> {
  content: T[]
  totalElements: number
  totalPages: number
  number: number
  size: number
  first: boolean
  last: boolean
}

export type ProblemStatus = "DRAFT" | "IN_REVIEW" | "PUBLISHED" | "UNLISTED" | "RETIRED"

export type ProblemDifficulty = "EASY" | "MEDIUM" | "HARD"

/**
 * How far the machine gate has got.
 *
 * `VERIFYING` is a real state rather than a spinner: the gate is four to six sandboxed runs and
 * takes tens of seconds, so a reviewer can genuinely open a problem mid-check.
 */
export type VerificationStatus = "UNVERIFIED" | "VERIFYING" | "PASSED" | "FAILED"

export type TestCaseKind = "SAMPLE" | "HIDDEN"

/**
 * What the caller may do next, decided by the SERVER.
 *
 * Served rather than re-derived here, so the state machine has one home. A console that computed
 * its own buttons would disagree with the backend the first time a rule changed, and the
 * disagreement would surface as a button that 409s.
 */
export type ProblemAction =
  | "EDIT"
  | "VERIFY"
  | "SUBMIT_FOR_REVIEW"
  | "WITHDRAW"
  | "APPROVE"
  | "REQUEST_CHANGES"
  | "PUBLISH"
  | "UNLIST"
  | "RETIRE"
  | "REPUBLISH"
  | "EDIT_APPROACH"

export interface ProblemSummary {
  problemId: string
  number: number | null
  slug: string
  title: string
  difficulty: ProblemDifficulty | null
  status: ProblemStatus
  verification: VerificationStatus
  topics: string[]
  languages: string[]
  /** Null below ten submissions — see the backend's ProblemResponseMapper for why. */
  acceptanceRate: number | null
  submissionCount: number
  submittedAt: string | null
  publishedAt: string | null
  updatedAt: string
}

export interface ProblemTopic {
  topicId: string
  slug: string
  name: string
  family: string
  familyLabel: string
  description: string | null
  problemCount: number
}

export interface ProblemTestCase {
  testCaseId: string
  position: number
  kind: TestCaseKind
  /** A JSON array of the arguments, in call order. */
  input: string
  /** ⚠ Generated by the reference solution, never typed by the author. */
  expected: string
  explanationHtml: string | null
}

/** One check from the publish gate. */
export interface VerificationCheck {
  id: string
  title: string
  status: "PASS" | "FAIL" | "WARN"
  detail: string | null
}

export interface VerificationReport {
  passed: boolean
  checks: VerificationCheck[]
  ranAt: string
  driverVersion: string | null
}

export interface ReviewEntry {
  reviewId: string
  action: string
  actorUserId: string
  actorName: string | null
  note: string | null
  createdAt: string
}

export interface ProblemDetail {
  problemId: string
  number: number | null
  slug: string
  title: string
  difficulty: ProblemDifficulty | null
  status: ProblemStatus
  authorUserId: string
  authorName: string | null

  harnessMode: string
  comparisonMode: string
  epsilon: number | null
  signature: unknown
  languages: string[]

  statementHtml: string
  constraintsHtml: string
  expectedTimeComplexity: string | null
  expectedSpaceComplexity: string | null
  revealFailingCase: boolean

  topics: ProblemTopic[]
  hints: string[]
  testCases: ProblemTestCase[]

  /** ⚠ The answers. Language id to source. */
  solutions: Record<string, string>
  /** Generated starter code, language id to source. Never stored. */
  stubs: Record<string, string>

  verificationStatus: VerificationStatus
  verification: VerificationReport | null
  verifiedAt: string | null

  approachHtml: string | null
  approachPublished: boolean
  approachUpdatedAt: string | null
  approachUpdatedBy: string | null

  submittedAt: string | null
  reviewNote: string | null
  publishedAt: string | null
  updatedAt: string

  reviewTrail: ReviewEntry[]
  availableActions: ProblemAction[]
}

export interface ReviewDecisionRequest {
  note?: string
}
